### PR TITLE
Parquet adaptor: Manage native underlying memory by AllocationManager

### PR DESCRIPTION
**Pull request by zhztheplayer**
Base changes rebased from https://github.com/apache/arrow/pull/5973

### CODE REVIEW

**Comment by zhztheplayer** [comment]
I have run several unit tests and now I'm more or less confident with this. @xuechendi Would you make a final check especially for the last commit about changes on the parquet adapter?

**Comment by xuechendi** [comment]
@zhztheplayer , got it! I'll check the codes and run test by end of tomorrow.

**Comment by xuechendi** [comment]
@zhztheplayer , I applied the PR onto master, and noticed this also required some spark side code change, can you also send out a link under this PR?
And for codes review, one of my concern is you changed some of arrow original codes under memory, and I don't think it is a proper way, since only if it will be merged to arrow in short term or this change will leave us struggling doing codes rebase in future.

**Comment by xuechendi** [comment]
@zhztheplayer , also submitted a small commit in your branch to fix some compile issue. including fixes for java doc and remove unused import.

**Comment by zhztheplayer** [comment]
> also submitted a small commit in your branch to fix some compile issue

Thanks @xuechendi .

> And for codes review, one of my concern is you changed some of arrow original codes under memory, and I don't think it is a proper way, since only if it will be merged to arrow in short term or this change will leave us struggling doing codes rebase in future.

Yes let's slow this down - once I had a discussion with @rongma1997 that we expected our memory allocation/release should work fine without doing such factoring. Besides I'm feeling the 2-level (RM+AM) reference management design is not that necessary in our case. So I think it's OK to keep our workaround until making contributions to upstream.

**Comment by xuechendi** [comment]
@zhztheplayer , I am not sure I understand your last sentence, when you say 
> So I think it's OK to keep our workaround until making contributions to upstream.
the walk-around you are mentioning is this PR or something else?

For first part of the content, I figured you and rong are working on another commit to replace this one, is that correct?

**Comment by zhztheplayer** [comment]
The method `AdaptorReferenceManger#retain`[1] is just our workaround. This PR is to replace it. Having this PR merged we could get Rong's PR[2] factored in similar way. However at this time I am inclined to hold this off since the workaround doesn't seem to bring any real problem to us.

[1] https://github.com/Intel-bigdata/arrow/blob/1d01a6bb28f3a309c72665c84f3fc1895160ea21/java/adapter/common/src/main/java/org/apache/arrow/adapter/common/AdaptorReferenceManager.java#L89-L92
[2] https://github.com/Intel-bigdata/SparkColumnarPlugin/pull/48

**Comment by zhztheplayer** [comment]
Closing

**Pull request closed without merging**
